version: '3.8'
services:
  server:
    container_name: 'cicd-container'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./src:/usr/app/src
